services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password

    volumes:
      - postgres-data:/var/lib/postgresql/data

  devops-api:
    image: tobywhitehead/devops-api:latest
    container_name: devops-api

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devopsdb
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: password

    ports:
      - "8080:8080"

volumes:
  postgres-data: